FROM postgres:alpine

ENV POSTGRES_USER=dbuser \
    POSTGRES_PASSWORD=dbpass \
    POSTGRES_DB=cities

EXPOSE 5432

RUN mkdir -p /docker-entrypoint-initdb.d
ADD ./src/main/resources/import-to-docker-postgres.sql /docker-entrypoint-initdb.d/import.sql
