FROM postgres:alpine

ENV POSTGRES_USER=dbuser \
    POSTGRES_PASSWORD=dbpass \
    POSTGRES_DB=mscitiesdb

EXPOSE 5432

RUN mkdir -p /docker-entrypoint-initdb.d
ADD ./ms-cities/src/main/resources/import-to-docker-postgres.sql /docker-entrypoint-initdb.d/ms-cities.sql
